namespace Nexus_API.Models.DTOs;

public record ClientResponse(
    int Id,
    string Фамилия,
    string Имя,
    string? Отчество,
    string СерияПаспорта,
    string НомерПаспорта,
    string СтатусКлиента,
    string НомерТелефона,
    string Email,
    string АдресРегистрации,
    string АдресПроживания,
    DateOnly ДатаРождения,
    string Пол,
    string? Снилс,
    string? Инн,
    string? Работодатель,
    string? ИсточникДохода,
    decimal? УровеньДохода,
    string? СемейноеПоложение,
    string? МестоРождения,
    string? КемВыданПаспорт,
    DateOnly ДатаВыдачиПаспорта,
    string? ДополнительныеСведения);

public record ClientCreateRequest(
    string Фамилия,
    string Имя,
    string? Отчество,
    string СерияПаспорта,
    string НомерПаспорта,
    string НомерТелефона,
    string Email,
    string АдресРегистрации,
    string АдресПроживания,
    DateOnly ДатаРождения,
    string Пол,
    string? Снилс,
    string? Инн,
    string? Работодатель,
    string? ИсточникДохода,
    decimal? УровеньДохода,
    string? СемейноеПоложение,
    string? МестоРождения,
    string? КемВыданПаспорт,
    DateOnly ДатаВыдачиПаспорта,
    string? ДополнительныеСведения);

public record ClientUpdateRequest(
    string? Фамилия,
    string? Имя,
    string? Отчество,
    string? НомерТелефона,
    string? Email,
    string? АдресПроживания,
    string? СтатусКлиента,
    string? Работодатель,
    string? ИсточникДохода,
    decimal? УровеньДохода,
    string? СемейноеПоложение,
    string? ДополнительныеСведения);